window.PROJECTS = [
  {
    id: "measurement-uncertainty-calculator",
    title: "측정 오차·불확도 계산기",
    description: "반복 측정값의 평균과 불확도를 계산하고 그래프·오차 원인까지 해석합니다.",
    type: "수업용 도구",
    category: "과학·탐구",
    url: "/apps/measurement-uncertainty-calculator/",
    tags: ["과학", "측정", "불확도", "통계", "그래프"],
    featured: true,
    thumbnail: "assets/thumbnails/measurement-uncertainty.webp",
    notice: "입력 자료는 서버로 전송되지 않음"
  },
  {
    id: "smartphone-sensor-physics-lab",
    title: "스마트폰 센서 물리 실험실",
    description: "스마트폰의 가속도·방향·자기장 센서를 기록하고 시간 그래프로 분석합니다.",
    type: "수업용 도구",
    category: "과학·탐구",
    url: "/apps/smartphone-sensor-physics-lab/",
    tags: ["물리", "센서", "가속도", "스마트폰", "실험"],
    featured: true,
    thumbnail: "assets/thumbnails/smartphone-sensor-lab.webp",
    notice: "실제 센서 측정은 HTTPS와 기기 권한 필요"
  },
  {
    id: "predict-response-board",
    title: "수업 전 예측·응답 보드",
    description: "실험 전 예측과 실험 후 응답을 익명으로 비교해 생각의 변화를 확인합니다.",
    type: "수업용 도구",
    category: "과학·탐구",
    url: "https://script.google.com/macros/s/AKfycbxZA-c5po0ofQtiPks3qkjYkhYXx824DpIDLyKXTrWwcvlK5vKnuDGsz54QCVF9vqbzmA/exec",
    tags: ["과학", "예측", "응답", "Apps Script", "수업"],
    featured: true,
    thumbnail: "assets/thumbnails/predict-response-board.webp",
    notice: "학생은 6자리 수업코드, 교사는 관리코드 사용"
  },
  {
    id: "mass-braking-distance",
    title: "질량과 제동거리",
    description: "질량과 속도가 제동거리에 미치는 영향을 직접 조작하며 탐구합니다.",
    type: "수업용 도구",
    category: "과학·탐구",
    url: "https://2026-mass-braking-distance.vercel.app",
    tags: ["물리", "운동", "시뮬레이션", "학생"],
    featured: true,
    thumbnail: "assets/thumbnails/mass.webp",
    notice: ""
  },
  {
    id: "motion-deductive-quiz",
    title: "배운 내용 확인하기",
    description: "물체의 운동을 단계별 질문으로 추론하는 참여형 물리 퀴즈입니다.",
    type: "수업용 도구",
    category: "과학·탐구",
    url: "https://2026-motion-deductive-inquiry-quiz.vercel.app",
    tags: ["물리", "추리", "퀴즈", "수업"],
    featured: true,
    thumbnail: "assets/thumbnails/motion.webp",
    notice: ""
  },
  {
    id: "science-inquiry-talk",
    title: "탐구톡 — 사이언스 챗봇",
    description: "정답 대신 질문과 증거로 학생이 스스로 과학 개념을 발견하도록 돕습니다.",
    type: "수업용 도구",
    category: "AI·수업 활동",
    url: "https://science-chatbot.bosound.workers.dev",
    tags: ["과학", "AI", "챗봇", "탐구", "수업"],
    featured: true,
    thumbnail: "assets/thumbnails/science-chatbot.webp",
    notice: "교사는 비밀키, 학생은 수업코드로 입장"
  },
  {
    id: "motion-energy-report-docs",
    title: "포물선 운동 분석 실험실",
    description: "동영상에서 포물선 운동 궤적과 에너지 변화를 분석하고 Google Docs 탐구 보고서로 제출합니다.",
    type: "수업용 도구",
    category: "과학·탐구",
    url: "https://script.google.com/macros/s/AKfycbxKS8oi71v0gin2XlyYLdVkJC4GD6xBusu0RJhMXrCkTfdHJ5VgxKar5ry2srvNCw8xXQ/exec",
    tags: ["Apps Script", "물리", "운동", "에너지", "보고서"],
    featured: false,
    thumbnail: "assets/thumbnails/report-docs.webp",
    notice: "학번·이름 입력 전 학교의 개인정보 운영 기준 확인"
  },
  {
    id: "science-report-slides",
    title: "과학 탐구 발표 슬라이드 작성기",
    description: "탐구 주제와 측정값을 입력해 Google Slides 발표 자료와 PDF를 자동 생성합니다.",
    type: "수업용 도구",
    category: "과학·탐구",
    url: "https://script.google.com/macros/s/AKfycbxY6L9Abkxfbnsp0uE9Vyjkxlk0qB5zkWKHq_fSFUYzE0bH9KVcKBWYPEu2tfcp-ZzXcg/exec",
    tags: ["Apps Script", "Google Slides", "PDF", "탐구", "발표"],
    featured: false,
    thumbnail: "assets/thumbnails/report-slide.webp",
    notice: "Google Drive 파일 생성 권한이 필요할 수 있음"
  },
  {
    id: "random-penalty-roulette",
    title: "랜덤뽑기",
    description: "최대 30명까지 번호·이름을 넣고, 뽑힌 항목을 제외하며 이어서 추첨합니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://2026-random-penalty-roulette.vercel.app",
    tags: ["룰렛", "랜덤 뽑기", "30명", "학급", "활동"],
    featured: false,
    thumbnail: "assets/thumbnails/roulette.webp",
    notice: ""
  },
  {
    id: "classroom-giant-timer",
    title: "초대형 타이머·스톱워치",
    description: "전자칠판에서 멀리서도 잘 보이는 타이머와 스톱워치로 수업 흐름을 관리합니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://2026-classroom-giant-timer.vercel.app",
    tags: ["타이머", "스톱워치", "전자칠판", "집중"],
    featured: false,
    thumbnail: "assets/thumbnails/giant-timer.webp",
    notice: "종료 알림음은 기기 음량 설정에 따라 재생"
  },
  {
    id: "classroom-ladder-draw",
    title: "사다리타기",
    description: "최대 30명의 이름과 결과를 넣고 경로를 따라가며 공정하게 짝·역할을 정합니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://2026-classroom-ladder-draw.vercel.app",
    tags: ["사다리타기", "30명", "역할", "랜덤"],
    featured: false,
    thumbnail: "assets/thumbnails/ladder-draw.webp",
    notice: "인원이 많을 때는 가로로 스크롤해 경로 확인"
  },
  {
    id: "classroom-group-maker",
    title: "모둠 편성기",
    description: "학생 명단을 붙여 넣거나 CSV로 불러와 이전 조합을 줄이며 모둠과 모둠장을 정합니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://2026-classroom-group-maker.vercel.app",
    tags: ["모둠", "명단", "CSV", "모둠장"],
    featured: false,
    thumbnail: "assets/thumbnails/group-maker.webp",
    notice: "명단과 이전 조합은 이 브라우저에만 저장"
  },
  {
    id: "classroom-seat-shuffler",
    title: "자리 바꾸기",
    description: "교실 행·열과 빈자리를 정하고 고정석을 유지한 채 최대 30명의 자리를 섞습니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://2026-classroom-seat-shuffler.vercel.app",
    tags: ["자리 바꾸기", "고정석", "빈자리", "명단"],
    featured: false,
    thumbnail: "assets/thumbnails/seat-shuffler.webp",
    notice: "좌석 설정과 명단은 이 브라우저에만 저장"
  },
  {
    id: "classroom-noise-character",
    title: "소음 레벨 캐릭터",
    description: "교실 소리를 기기 안에서만 분석해 캐릭터 표정과 색으로 조용한 정도를 보여 줍니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://2026-classroom-noise-character.vercel.app",
    tags: ["소음", "마이크", "집중", "캐릭터"],
    featured: false,
    thumbnail: "assets/thumbnails/noise-character.webp",
    notice: "마이크 권한 필요 · 음성은 녹음하거나 서버로 전송하지 않음"
  },
  {
    id: "classroom-team-scoreboard",
    title: "모둠 점수판",
    description: "최대 10개 모둠의 점수를 빠르게 더하고 되돌리며 목표 점수 달성을 함께 확인합니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://2026-classroom-team-scoreboard.vercel.app",
    tags: ["모둠", "점수판", "전자칠판", "수업"],
    featured: false,
    thumbnail: "assets/thumbnails/team-scoreboard.webp",
    notice: "점수는 이 브라우저에만 저장"
  },
  {
    id: "quick-understanding-poll",
    title: "빠른 이해도 투표",
    description: "학생이 QR 또는 6자리 코드로 참여하고 교사가 결과 공개 시점을 정하는 즉석 이해도 투표입니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://script.google.com/macros/s/AKfycbyraQFQYdh7Gptf4NjG2A560317W3oKgZPtwxR5xTAOxmp25qZWrA5ItS4yiSJBcXIXQg/exec",
    tags: ["투표", "QR", "이해도", "Apps Script"],
    featured: false,
    thumbnail: "assets/thumbnails/understanding-poll.webp",
    notice: "별칭과 응답은 교사가 삭제할 때까지 전용 스프레드시트에 보관"
  },
  {
    id: "speed-quiz-board",
    title: "순발력 OX·초성 퀴즈판",
    description: "학생이 QR로 입장해 OX·초성 문제에 답하고 정답과 응답 속도로 점수를 얻는 퀴즈판입니다.",
    type: "수업 보조 도구",
    category: "AI·수업 활동",
    url: "https://script.google.com/macros/s/AKfycbyAiaBE-mm19i6gtvdnSqdl0Y0ox-4XOIi92Z_kYl7uyGmNkpYVAQPSeIb2cNdXa8045g/exec",
    tags: ["OX 퀴즈", "초성 퀴즈", "QR", "Apps Script"],
    featured: false,
    thumbnail: "assets/thumbnails/speed-quiz.webp",
    notice: "별칭과 응답은 교사가 삭제할 때까지 전용 스프레드시트에 보관"
  },
  {
    id: "training-sign-registry",
    title: "연수서명부",
    description: "연수 참석자 서명을 수집하고 등록 현황을 관리하는 Apps Script 서명부입니다.",
    type: "업무용 도구",
    category: "교사 업무",
    url: "https://script.google.com/macros/s/AKfycbwAMCLBd3sJYo8CBs7Qi01qQZQ5NV2CHaYjLJQFokPd012fylnGjLBiaN3c64sk7Pi9cg/exec",
    tags: ["서명", "연수", "Apps Script", "교사"],
    featured: false,
    thumbnail: "assets/thumbnails/sign.webp",
    notice: ""
  },
  {
    id: "ipad-soundboard",
    title: "스마트 교무실 호출벨",
    description: "복도 단말에서 교사를 선택해 교무실 블루투스 스피커로 안내하는 호출 도구입니다.",
    type: "업무용 도구",
    category: "교사 업무",
    url: "https://smart-teacher-call.vercel.app",
    tags: ["호출", "태블릿", "노트북", "블루투스", "교사"],
    featured: false,
    thumbnail: "assets/thumbnails/smart-teacher-call-v2.webp",
    notice: "기본 이름은 익명이며, 이름 관리에서 기기별로 변경·저장"
  },
  {
    id: "teacher-calendar",
    title: "교사용 일정 달력",
    description: "수업과 업무 일정을 간결하게 기록하고 확인하는 교사용 달력입니다.",
    type: "업무용 도구",
    category: "교사 업무",
    url: "https://teacher-calendar-iota.vercel.app",
    tags: ["달력", "일정", "업무", "교사"],
    featured: false,
    thumbnail: "assets/thumbnails/calendar.webp",
    notice: ""
  },
  {
    id: "mp3-silence-adder",
    title: "MP3 묵음 추가기",
    description: "오디오 앞뒤에 원하는 길이의 묵음을 손쉽게 덧붙입니다.",
    type: "업무용 도구",
    category: "생활·창작 도구",
    url: "https://mp3-silence-adder.vercel.app",
    tags: ["MP3", "오디오", "편집", "창작"],
    featured: false,
    thumbnail: "assets/thumbnails/mp3.webp",
    notice: ""
  }
];
