import { downsample, magnitude, normalizeSample, parseCsv, summarize } from "./sensor-core.js";
const $=s=>document.querySelector(s); const colors={x:"#ff7657",y:"#55bfd0",z:"#f2c84b",alpha:"#ff7657",beta:"#55bfd0",gamma:"#f2c84b",magnitude:"#79b98a"};
let mode="acceleration", state="idle", samples=[], sensor=null, startTime=null, pausedAt=0, lastAt=null, intervals=[], raf=0;
const keys=()=>mode==="orientation"?["alpha","beta","gamma","magnitude"]:["x","y","z","magnitude"];
function supportText(){ if(!window.isSecureContext && location.hostname!=="localhost")return ["insecure","보안 연결(HTTPS)이 필요합니다."]; if(mode==="magnetometer")return "Magnetometer" in window?["supported","자기장 센서를 사용할 수 있습니다."]:["missing","이 브라우저는 자기장 센서를 지원하지 않습니다. 예제 또는 CSV를 사용하세요."]; const event=mode==="acceleration"?"DeviceMotionEvent":"DeviceOrientationEvent"; return event in window?["supported","센서 이벤트를 지원합니다. iOS에서는 버튼을 눌러 권한을 허용하세요."]:["missing","센서 이벤트를 지원하지 않습니다. 예제 또는 CSV를 사용하세요."]; }
function diagnose(){const [kind,text]=supportText();$("#support").textContent=`${kind==="supported"?"● 지원":"△ 확인 필요"} · ${text}`;}
async function permission(){try{const ctor=mode==="acceleration"?window.DeviceMotionEvent:window.DeviceOrientationEvent;if(ctor?.requestPermission){const result=await ctor.requestPermission();if(result!=="granted")throw new Error("권한이 거부되었습니다. 브라우저 설정에서 다시 허용해 주세요.");}$("#support").textContent="● 권한 준비 완료 · 기록 시작을 누르세요.";}catch(error){$("#support").textContent=`× ${error.message}`;}}
function setMode(next){stop(true);mode=next;document.querySelectorAll(".mode").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));samples=[];renderToggles();diagnose();render();}
function renderToggles(){$("#toggles").innerHTML=keys().map(k=>`<label><input type="checkbox" data-key="${k}" checked><span style="color:${colors[k]}">━</span> ${k}</label>`).join("");document.querySelectorAll("#toggles input").forEach(i=>i.addEventListener("change",render));}
function activeKeys(){return [...document.querySelectorAll("#toggles input:checked")].map(i=>i.dataset.key);}
function push(raw, timestamp=performance.now(), source="sensor"){if(state!=="recording"&&source==="sensor")return;if(startTime===null)startTime=timestamp-pausedAt;const elapsed=timestamp-startTime; samples.push(normalizeSample(mode,elapsed,raw,source));if(lastAt!==null)intervals.push(timestamp-lastAt);lastAt=timestamp;if(elapsed>Number($("#duration").value)*1000)stop();}
function start(){if(!$("#safe").checked){$("#support").textContent="△ 시작 전 안전 확인에 체크해 주세요.";return;}if(state==="recording")return;state="recording";$("#start").disabled=true;$("#pause").disabled=false;$("#stop").disabled=false;if(!attach()){state="idle";$("#start").disabled=false;$("#pause").disabled=true;$("#stop").disabled=true;return;}loop();}
function attach(){try{if(mode==="magnetometer"){sensor=new Magnetometer({frequency:30});sensor.addEventListener("reading",()=>push({x:sensor.x,y:sensor.y,z:sensor.z}));sensor.addEventListener("error",e=>$("#support").textContent=`× 자기장 센서 오류: ${e.error?.message||"알 수 없음"}`);sensor.start();}else if(mode==="acceleration"){sensor=e=>{const a=e.acceleration&&[e.acceleration.x,e.acceleration.y,e.acceleration.z].some(v=>v!==null)?e.acceleration:e.accelerationIncludingGravity;if(a)push({x:a.x,y:a.y,z:a.z,includesGravity:a===e.accelerationIncludingGravity},e.timeStamp);};window.addEventListener("devicemotion",sensor);}else{sensor=e=>push({alpha:e.alpha,beta:e.beta,gamma:e.gamma},e.timeStamp);window.addEventListener("deviceorientation",sensor);}return true;}catch(e){$("#support").textContent=`× 센서를 시작할 수 없습니다: ${e.message}`;sensor=null;return false;}}
function detach(){if(mode==="magnetometer"&&sensor?.stop)sensor.stop();else if(mode==="acceleration"&&sensor)window.removeEventListener("devicemotion",sensor);else if(sensor)window.removeEventListener("deviceorientation",sensor);sensor=null;}
function pause(){if(state!=="recording")return;state="paused";pausedAt=samples.at(-1)?.elapsed_ms||0;detach();$("#start").disabled=false;$("#start").textContent="이어 기록";$("#pause").disabled=true;cancelAnimationFrame(raf);render();}
function stop(silent=false){if(state==="recording"||state==="paused")detach();state="idle";pausedAt=0;startTime=null;lastAt=null;$("#start").disabled=false;$("#start").textContent="기록 시작";$("#pause").disabled=true;$("#stop").disabled=true;cancelAnimationFrame(raf);if(!silent)render();}
function clear(){stop(true);samples=[];intervals=[];render();}
function loop(){render();if(state==="recording")raf=requestAnimationFrame(loop);}
function render(){const end=samples.at(-1)?.elapsed_ms||0;$("#timer").textContent=`${String(Math.floor(end/60000)).padStart(2,"0")}:${(end%60000/1000).toFixed(1).padStart(4,"0")}`;const avg=intervals.length?intervals.reduce((a,b)=>a+b,0)/intervals.length:null;$("#meta").textContent=`${state==="recording"?"기록 중":state==="paused"?"일시정지":"대기"} · ${samples.length}개 · 실제 간격 ${avg?avg.toFixed(1)+" ms":"—"}`;draw();renderSummary();}
function draw(){const canvas=$("#plot"),ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,p={l:58,r:22,t:22,b:40};ctx.clearRect(0,0,w,h);ctx.fillStyle="#0d223d";ctx.fillRect(0,0,w,h);const data=downsample(samples);const selected=activeKeys();let vals=data.flatMap(r=>selected.map(k=>r[k])).filter(Number.isFinite);let limit=Number($("#scale").value)||Math.max(1,...vals.map(Math.abs))*1.12;let min=mode==="orientation"&&$("#scale").value==="auto"?Math.min(-1,...vals): -limit,max=mode==="orientation"&&$("#scale").value==="auto"?Math.max(1,...vals):limit;const tmax=Math.max(Number($("#duration").value)*1000,data.at(-1)?.elapsed_ms||1);const x=t=>p.l+t/tmax*(w-p.l-p.r),y=v=>p.t+(max-v)/(max-min)*(h-p.t-p.b);ctx.strokeStyle="#2b4058";ctx.fillStyle="#91a5ba";ctx.font="12px monospace";for(let i=0;i<=4;i++){let yy=p.t+(h-p.t-p.b)*i/4;ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke();ctx.fillText((max-(max-min)*i/4).toFixed(1),5,yy+4);}selected.forEach(key=>{ctx.strokeStyle=colors[key];ctx.lineWidth=key==="magnitude"?3:2;ctx.setLineDash(key==="magnitude"?[8,5]:[]);ctx.beginPath();let begun=false;data.forEach(row=>{if(!Number.isFinite(row[key]))return;const px=x(row.elapsed_ms),py=y(row[key]);begun?ctx.lineTo(px,py):ctx.moveTo(px,py);begun=true;});ctx.stroke();});ctx.setLineDash([]);ctx.fillText(`${(tmax/1000).toFixed(1)} s`,w-70,h-12);}
function renderSummary(){const from=Number($("#from").value)*1000,to=Number($("#to").value)*1000;const stats=summarize(samples,keys(),from,to);$("#summary").innerHTML=keys().map(k=>{const s=stats[k];return `<div>${k}<b>${s?`평균 ${s.mean.toFixed(2)}<br>최소 ${s.min.toFixed(2)} · 최대 ${s.max.toFixed(2)}<br>n=${s.n}`:"자료 없음"}</b></div>`}).join("");}
function example(){stop(true);samples=[];mode=mode;for(let t=0;t<=10000;t+=50){if(mode==="orientation")samples.push(normalizeSample(mode,t,{alpha:(t/50)%360,beta:25*Math.sin(t/700),gamma:15*Math.cos(t/900)},"example"));else samples.push(normalizeSample(mode,t,{x:2*Math.sin(t/350),y:1.2*Math.cos(t/500),z:(mode==="acceleration"?9.8:32)+3*Math.sin(t/900),includesGravity:mode==="acceleration"},"example"));}$("#to").value=10;render();}
function importFile(file){const reader=new FileReader();reader.onload=()=>{try{stop(true);const imported=parseCsv(reader.result);const importedMode=imported.find(row=>["acceleration","orientation","magnetometer"].includes(row.sensor_mode))?.sensor_mode;if(importedMode&&importedMode!==mode){mode=importedMode;document.querySelectorAll(".mode").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));renderToggles();}samples=imported;$("#to").value=((samples.at(-1)?.elapsed_ms||0)/1000).toFixed(1);render();$("#support").textContent=`● 가져온 ${mode} 자료 ${samples.length}개를 분석 중입니다.`;}catch(e){$("#support").textContent=`× CSV 오류: ${e.message}`;}};reader.readAsText(file);}
function download(){if(!samples.length)return;const headers=["elapsed_ms",...keys(),...(mode==="acceleration"?["includes_gravity"]:[]),"source","sensor_mode"];const rows=[headers.join(","),...samples.map(r=>headers.map(h=>h==="sensor_mode"?mode:(r[h]??"")).join(","))];const url=URL.createObjectURL(new Blob(["\ufeff"+rows.join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`${($("#title").value||"센서실험").replace(/[\\/:*?"<>|]/g,"_")}.csv`;a.click();URL.revokeObjectURL(url);}
document.querySelectorAll(".mode").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));$("#permission").onclick=permission;$("#start").onclick=start;$("#pause").onclick=pause;$("#stop").onclick=()=>stop();$("#clear").onclick=clear;$("#example").onclick=example;$("#download").onclick=download;$("#file").onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);["from","to","scale","duration"].forEach(id=>$("#"+id).addEventListener("input",render));document.addEventListener("visibilitychange",()=>{if(document.hidden&&state==="recording")pause();});window.addEventListener("pagehide",()=>stop(true));renderToggles();diagnose();render();
